### ISSUE TITLE
Many measurements say `failure = true` & `anomaly = false`

### ISSUE THREAD

**Issue by hellais** [ooni/api#59]
It was pointed out that this is the case for measurements in MY by @ kaerumy in https://github.com/ooni/api/issues/32#issuecomment-340647624.

**Comment by hellais** [comment]
The root cause of this bug is actually inside of the pipeline though. @darkk do you have any ideas why this may be happening?

**Comment by kaerumy** [comment]
It's not just MY, but also KH 

https://api.ooni.io/api/v1/measurements?offset=100&input=https%3A%2F%2Fwww.cambodiadaily.com%2F&limit=100&probe_cc=KH

https://explorer.ooni.torproject.org/measurement/20180209T061659Z_AS38901_n9ZzV6qX24wiMWjFykrOTHZM1iY0Qy9Tl7Apq4vuR9DENUZEq4?input=https:%2F%2Fwww.cambodiadaily.com%2F

**Comment by hellais** [comment]
So I am looking at the DB rows for a sample of these measurements running the query:

```
SELECT 
	measurement.test_runtime,
	input.input,
	measurement.measurement_start_time,
	report.probe_cc,
	report.probe_asn,
	report.probe_ip,
	report.report_id,
	http_verdict.http_experiment_failure,
	http_verdict.blocking,
	measurement.anomaly,
	measurement.msm_failure,
	measurement.exc,
	measurement.residual_no,
	residual.residual
FROM measurement 
JOIN input ON input.input_no = measurement.input_no 
JOIN report ON report.report_no = measurement.report_no
JOIN http_verdict ON http_verdict.msm_no = measurement.msm_no
JOIN software ON software.software_no = report.software_no
JOIN residual ON residual.residual_no = measurement.residual_no
WHERE probe_cc = 'MY'
LIMIT 10;
```

I notice that they all have `anomaly` and `msm_failure` set to `NULL` and have a non-null `residual_no` (which is a condition to mark the measurement as failed).

Here is a sample of a residual from a measurement:

```
{"test_keys": {"agent": "", "queries": [{"engine": "", "query_type": "", "resolver_port": null}], "retries": null, "requests": [{"response": {"response_line": ""}}, {"response": {"response_line": ""}}, {"response": {"response_line": ""}}], "socksproxy": null}, "probe_city": null, "annotations": {"platform": "", "engine_name": "", "engine_version": "", "engine_version_full": ""}, "bucket_date": "", "test_helpers": {"backend": {"type": "", "address": ""}}, "backend_version": null, "data_format_version": ""}
```

My understanding is that the residual is stuff that the pipeline doesn't know how to ingest properly and it will therefore not mark the measurements in any way.
Is this correct?

**Comment by darkk** [comment]
I've updated the title to reflect reality a bit better.

The story is:
1. every measurement that has some non-ingested (unknown values, unknown fields, malformed data in fields) data is flagged as "failed"
2. the reason is &mdash; there is something going on there that pipeline does not know how to handle, so it does it's "best", flags the measurement and moves on
3. the reason for high percentage of "failed" measurements is that any automatic reasoning on top of data needs reliable signals. No signal is better than lots of false alarms.
4. I see no good reason to invest time into data cleanup if the signal we get after cleanup is "too weak" to be useful (if it has too high number of false positives)

So I would say, if you know what you're doing and you're sure about the data then feel safe to ignore `failure: true` marker, it's probably not of great use right now :-)

The overall plan to reduce number of measurements flagged as `failure: true` is
- enrich web_connectivity test to get more new signals and get more detailed signals
- ingest the signals and build heuristics on top of the signals
- do data cleanup as new signals will make the data more "actionable" for robots
- alert on high amount of "failed" measurements to catch bugs in OONI Probe

**Comment by hellais** [comment]
> every measurement that has some non-ingested (unknown values, unknown fields, malformed data in fields) data is flagged as "failed"

Can you link me to where I can see what the schema the pipeline expects is? I can maybe see if I can adjust the parser to make it happy about the above.

Or do you understand from the residual, what fields are unexpectedly missing or present?

> the reason is — there is something going on there that pipeline does not know how to handle, so it does it's "best", flags the measurement and moves on

I guess this makes sense, yet we should document what to do in this case and how we can resolve it.

> the reason for high percentage of "failed" measurements is that any automatic reasoning on top of data needs reliable signals. No signal is better than lots of false alarms.

This makes sense.

> I see no good reason to invest time into data cleanup if the signal we get after cleanup is "too weak" to be useful (if it has too high number of false positives)

I am not sure this is the case for these particular types of measurements as it seems like there is enough data to draw some conclusion, my understanding is that the ingested data contains several **extra** fields that the pipeline does not recognise.

I am thinking that in general, perhaps, it's wise if we can still ingest data and mark things as we should so long as it contains a subset of the required data. If it contains more data than it should I think we should maybe flag it as "some extra data is there", but still ingest it.

What do you think?

**Comment by darkk** [comment]
> Can you link me to where I can see what the schema the pipeline expects is?

The schema is the code itself. It's done that way as OONI did not enforce schema on incoming data for years and enforcing that now will likely break something. The process to change that (slowly, without loosing any data) and, maybe, introduce schema validation eventually is the story of those "residuals". "Residuals" are approximation of "the fields unknown to the pipeline" (data in "residuals" scheme is dropped, but data type is preserved, so similar residuals are groupped together).

> we should document what to do when _the pipeline flags the measurement and moves on_ and how we can resolve it.

I have [some process](https://github.com/ooni/api/issues/59#issuecomment-430600235) in mind, but to make the process practical, it needed some code. Namely:

- partial re-processing, so re-processing of the single measurement from the bucket does not trigger re-processing of the whole bucket &mdash; that was done long time ago
- fast filter for "similar" webpages to lookup candidates for reprocesing when new webpage fingerprint is added &mdash; that finally converged ~ a week ago
- avoid re-computation of simhashes on re-ingestion as it takes really significant portion of CPU time

The similarity story was a requirement as blockpage fingerprint is currently single "reliable" datapoint to mark the anomaly `confirmed` and re-processing of whole dataset checking for regexp takes days (it actually took almost a month and triggered hardware incident during last full-scan), so speedup is crucial here.

So, finally, the hard part of step-one of the aforementioned process is almost over (there is some manual labor regarding data markup, but 1) it's trivial and 2) it's not blocker for Khairil's use-case), so finally step-two makes sense to take.

> I am not sure this is the case for these particular types of measurements

Exactly! On one hand, that's why I could live in happy stoicism having ~100% failed measurements when update of blockpage fingerprint dataset was prohibitevly slow, and on another hand, that's why I have _"do data cleanup for the measurements showing blockpages / resolving domains to blockervers"_ as the second bullet point in the plan.

Indeed, as soon as we can update blockpage fingerprint dataset easily (without waiting for days for each single update to happen) data quality starts to matter. One of the ways to resolve that is to draw a borderline if "unknown" fields matter or not in some specific cases. Another way is to do cleanup having a way to define a slice of the dataset that _"matters most"_.

I'm going to follow the second way for a while (as it's more "generic" way and does not introduce any "special" cases) and if it turns out to be impractical, I'd switch to the first one.


> it's wise if we can still ingest data and mark things as we should so long as it contains a subset of the required data. If it contains more data than it should I think we should maybe flag it as "some extra data is there", but still ingest it.

Pipeline ingests all the data that can be ingested trivially and [slightly](https://github.com/ooni/pipeline/blob/62f30b74e4b080385a452bf843530aa0ddc751e8/af/shovel/centrifugation.py#L574-L575) [more](https://github.com/ooni/pipeline/blob/62f30b74e4b080385a452bf843530aa0ddc751e8/af/shovel/oonipl/pg.py#L39-L107).

And `failed` flag presented in the API is actually a combination of various flags present in the database.

I'm not 100% confident that it's the best way to handle all the cases, but I currently treat semantics of three API flags in a following way:

- `confirmed` &mdash; we believe that the measurement contains sample of network filtering
- `anomaly` &mdash; we believe that the measurement contains some network anomaly
- `failed` &mdash; if the flag is clean, we believe that the datapoint can be used in automatic processing and does not need human attention that much

_"We believe"_ disclaimer is important &mdash; all of these flags may change when we add various heuristics, here are some imaginary examples:

- `confirmed` false → true: we add new fingerprint of the blockpage
- `confirmed` true → false: we refine fingerprint of the blockpage as the old fingerprint captured some news article in some media
- `anomaly` false → true: measurement failed to dial TH, so OONI Probe was unable to register anomaly autonomlulsy, but the fetched page matches fingerprint, so it becomes confirmed anomaly
- `anomaly` true → false: we add heuristic that filters out anomalies for well-known GeoDNS load-balanced domains that present different content depending on the expected user's language
- `failed` true → false: we extend pipeline to ingest previously unknown fields
- `failed` false → true: we enforce schema and mandatory fields are missing

**Comment by hellais** [comment]
Thanks for looking into this @darkk and your answers to the above mentioned points are very instructive.

Can you also comment and what you believe are the next steps needed to start marking the measurements linked by @kaerumy as `anomaly=true` and `failure=false`?

From the looks of it, for example https://api.ooni.io/api/v1/measurements?offset=100&input=https%3A%2F%2Fwww.cambodiadaily.com%2F&limit=100&probe_cc=KH, still presents many (most?) `failure=true`.

Do we know which are the unknown fields present in these measurements and how we can adjust the parser to start recognising them?

**Comment by bassosimone** [comment]
FWIW, I've just been hit by this issue for Jordan. Then come back to the issue, re-read the whole thread and remembered the whole story. It's fine, I guess, to basically ignore `failure` for now. (TBH it seems to me that this should probably be called `automatic_processing_possible` but that's a second order comment.)

**Comment by hellais** [comment]
I have ran into issues related to this while working on the metrics for explorer.

What I have noticed is that:
```
SELECT * FROM measurement WHERE confirmed!=null AND measurement_start_time > current_date - interval '30 day';

SELECT * FROM measurement WHERE anomaly!=null AND measurement_start_time > current_date - interval '30 day';
```

Both will return 0 rows (basically all recent measurements have the `anomaly` and `confirmed` columns set to `NULL`).

Many of these measurements actually have a good signal in them and should be flagged at the very least as `anomaly` and some probably as `confirmed`.

@darkk can you advise on what is the best way to move forward on this? I would be glad to help out with this issue and write some code to fix the ingestion of these measurements.

**Comment by hellais** [comment]
I started digging a bit into this, and I cannot seem to find where the `anomaly` and `confirmed` flags are being set by the pipeline (for example in: https://github.com/ooni/pipeline/blob/master/af/shovel/centrifugation.py).

The only reference to `anomaly` and `confirmed` is in: https://github.com/ooni/pipeline/blob/master/af/oometa/005-anomaly-flags.install.sql#L28, but it seems like this is not run on every tick of the pipeline. Is this the case?

**Comment by darkk** [comment]
Speaking of `failure` the story is very simple and iterative: residuals should be cleaned up and starting with the "most relevant" subset helps a lot to focus. Yes, we do know the unknown fields, they're listed as residuals. However, there is a minor problem to solve here: IIRC `residual` and `exc` fields are not updated on _reprocessing_. Reprocessing touches only defined subset of tables and corresponding subset of code paths, so cleaning `exc` on reprocessing is an incorrect action to do. It's _reingestion_ that should update `exc`. I don't remember if it actually updates `exc`, but it's trivial to test that.

> Is this the case?

It is. We never converged on a precise definition of `confirmed` given a complex history of "in-depth measurements" projects, so `confirmed` and `anomaly` currently are just [proof-of-concept stubs(!)](https://github.com/ooni/pipeline/blob/4a3a014256e4c2b46fc693d732da4e16aba3f0dd/af/oometa/005-anomaly-flags.install.sql#L22-L30). Some time ago we agreed that having non-updated PoC was a reasonable way to signal the lack of consensus while having some sample data for Explorer mock-ups. As we see, the state of the affairs has not changed much and those discussions are still deadlocked after both being moved forward and being rolled back.

I think, the practical way to serve **the current needs** of Explorer UI/UX development is to shilly-shally a bit further and codify the aforecited rules into something that is updated regularly and can be trivially updated with some other set of rules. Although, I still consider those rules too questionable for my interpretation of the word "`confirmed`".

**Comment by hellais** [comment]
> : residuals should be cleaned up and starting with the "most relevant" subset helps a lot to focus.

I have updated the relevant pipeline issue on this and your input and comments there are required:
https://github.com/ooni/pipeline/issues/112#issuecomment-476188316

> confirmed and anomaly currently are just proof-of-concept stubs

I see, it was not clear to me from the documentation or discussions that this was the case.

I have filed a ticket for work related to this in: https://github.com/ooni/pipeline/issues/146

**Comment by darkk** [comment]
> it was not clear to me from the documentation or discussions

I'm sorry that miscommunication happened. I assumed that it was clear as you also were naming those columns "dummy" in discussions :-)

**Comment by hellais** [comment]
We have now rolled out a update to the pipeline which populated the `anomaly` and `confirmed` flags properly for all measurements. 🎉 

There are still several measurements which say `failure=true` due to there being some unparsed data in them (this issue is tracked as part of: https://github.com/ooni/pipeline/issues/112).

@kaerumy can you see if it's now working for your use-case?

You may also be interesting in setting up your own copy of our metadb and synching it. The completion of this is tracked as part of: https://github.com/ooni/sysadmin/issues/272.

**Comment by bassosimone** [comment]
Epic news!!!

**Comment by kaerumy** [comment]
Great work!

Initially working for some Malaysian data for 2019.

![image](https://user-images.githubusercontent.com/1060743/56364704-caf4e280-6221-11e9-9237-48e8b2428524.png)

Now we can start seeing overview anomalies, confirmed and test coverage across our region (and others)

**Comment by hellais** [comment]
That is great to hear @kaerumy. If you have any other issues please to let us know either by opening a new issue or on slack.
