### ISSUE TITLE
Optimise the queries used by the endpoints to obtain reasonable performance

### ISSUE THREAD

**Issue by gabelula** [ooni/api#62]
With focus on the integration layer for OONI Explorer.

**Comment by hellais** [comment]
Since:
https://github.com/ooni/api/pull/66
https://github.com/ooni/api/pull/70
https://github.com/ooni/api/pull/74
https://github.com/ooni/api/pull/63

We are capturing queries which timeout and recording them inside of sentry.

The work of optimising queries is not necessarily going to ever be fully completed (we don't know all the possible future queries), but at least we know have the exceptions logged and measured so we can do more passes at fixing them.

I have already done a little bit of optimisation of some queries and some tables for OONI Explorer and will do more of this once I have moved the API onto the production.
