### ISSUE TITLE
Drop secrets.tar.enc from travis

### ISSUE THREAD

**Issue by bassosimone** [ooni/api#84]
```
$ openssl aes-256-cbc -K $encrypted_965b8cbf2a7d_key \
    -iv $encrypted_965b8cbf2a7d_iv -in secrets/secrets.tar.enc \
    -out secrets/secrets.tar -d
iv undefined
The command "openssl [...]" failed and exited with 1 during .
```

See https://travis-ci.org/ooni/api/builds/512617276

I would assume this depends on the travis configuration and some bits of that have changed so that $encrypted_965b8cbf2a7d_key is not defined anymore.

Spotted when merging #82

**Comment by hellais** [comment]
That is normal. As a security precaution we don't allow decrypting the secrets.tar.enc file when running the CI on a branch or PR not opened by an authorised github user.

That said since we don't do continous delivery of the API anymore with docker-compose we can probably remove the secrets/* and drop all the relevant travis.yml strings.

**Comment by bassosimone** [comment]
Thanks! I’ll update the issue title accordingly!

**Comment by bassosimone** [comment]
Oh you did that already:)

**Comment by hellais** [comment]
This is done.
